### ISSUE TITLE
Don't parse human-friendly error messages

### ISSUE THREAD

**Issue by seanh** [hypothesis/publisher-account-test-site#20]
The publisher test site currently contains code that parses error messages intended for humans to read, which is brittle: https://github.com/hypothesis/publisher-account-test-site/blob/master/app.py#L35

The h API doesn't provide machine-readable error codes so there's no good way to the test site to do this.

We should redesign the test site somehow so that it doesn't have to parse error messages from the h API.

**Comment by seanh** [comment]
One possible workaround might be:

Don't try to automatically create a user account in h when the user logs in to the publisher test site. Instead have separate sign up and log in forms on the test site:

* The sign up form would call the API to create the user in h. If the API responds with an error, e.g. because the user account already exists, the sign up form will just show this error to the user. (It doesn't need to parse the error message, just blindly display it.)

* The log in form will just assume the user exists in h and try to log in, and if log in fails then show an error. This might be awkward though as I think it would actually be the _client_ that gets the error, when it tries to do a grant token exchange with h, not the test site. And I don't think the client has a good error state when this happens. This should probably be fixed in the client.

* It will be up to the user to use the sign up form to create an account before using the log in form to login to the same account.

**Comment by robertknight** [comment]
The intention is that the example site should provide an experience/flow that is representative of what would happen on an actual publisher's site, so it would make sense to separate "Sign up" from "Log in". I avoided doing this up to now just to keep things a bit simpler.

> The log in form will just assume the user exists in h and try to log in, and if log in fails then show an error.

If the h service had an API that enabled the publisher to list registered accounts then the example site could make that call on startup in order to populate an in-memory set of valid user IDs. It could then display an appropriate error on login. Alternatively, just store the set of valid user IDs in a CSV file or something dumb like that.

> We should redesign the test site somehow so that it doesn't have to parse error messages from the h API.

Or we make error messages from the h API machine readable. 😛

**Comment by lyzadanger** [comment]
Fixed by #28 , I believe!
